<script>
    //  How to use error handling method Try and Catch in Promise Async/Await In JavaScript . 
    //  Today we will cover async-await javascript error handling.
    const pobj1 = new Promise((resolve,reject)=>{
    setTimeout(()=>{
         let rollno =[1,2,3,4,5];
         resolve(rollno)
         //reject('error not get')
    },2000)

})
const getbiodata = (indexdata)=>{
    return new Promise((resolve,reject)=>{
        setTimeout((indexdata)=>{
            const biodata={
                    name:"muki",
                    classw:"2nd"
                }
                resolve(` my roll no is ${indexdata} and my name is ${biodata.name} , i am read in ${biodata.classw}`)
        },2000,indexdata)

    })
}


async function getdata(){
try{
    const rollNo = await pobj1;
 console.log(rollNo);
 const bio = await getbiodata(rollNo[2]);
 console.log(bio);
 return bio;
}  catch(error){
    console.log(` the Error : - ${error}`);

}

}
const datame= getdata().then((myname)=>{
    console.log(myname);
});
</script>